#!/usr/bin/env python
"""
Usage: main [ ( -l <level> | -s <scene> ) ]

Options:
    -l, --level <level>  start with level x
    -s, --scene <scene>  start with scene x
"""

import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from engine.app import App
from scenes.game import Game
from scenes.menu import MainMenu

from docopt import docopt
arguments = docopt(__doc__)

app = App(title="One Whale Trip",
          resolution=(800, 480),
          scenes=[MainMenu, Game],
          entry=arguments['--scene'] or "Game",
          level_nr=arguments['--level'] or 1
          )
app.run()
