#!/usr/bin/env python
"""
Usage: main [ ( -l <level> | -s <scene> ) ] [ -f <fullscreen> ]

Options:
    -l, --level <level>  start with level x
    -s, --scene <scene>  start with scene x
    -f, --fullscreen
"""

import pygame
import sys
import os

sys.path.insert(0, os.path.join(os.path.dirname(__file__), 'src'))
sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', 'src'))

from engine.app import App
from scenes.game import Game
from scenes.menu import MainMenu
from scenes.intro import Intro
from scenes.outro import Outro
from scenes.gameover import GameOver
from scenes.cutscene import CutScene
from scenes.victory import Victory

from docopt import docopt
arguments = docopt(__doc__)

TITLE = "One Whale Trip"
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 480

pygame.init()

app = App(TITLE, SCREEN_WIDTH, SCREEN_HEIGHT, arguments['--fullscreen'],
          scenes=[Intro, MainMenu, Game, GameOver, CutScene, Victory, Outro],
          entry=arguments['--scene'] or "Game",
          level_nr=arguments['--level'] or 0
          )

app.run()
pygame.quit()
